// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://grvcrwbhrispwzodlret.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdydmNyd2JocmlzcHd6b2RscmV0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTczODczODksImV4cCI6MjA3Mjk2MzM4OX0.PYP_A-mVn6ikJ69Al-Otckat3HZDiVmg3vDtzpseEuk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});